version: '3'
services:
  app:
    build: ./frontend-stori
    ports:
      - 3001:3000
    depends_on:
      - api
    env_file:
      - ./frontend-stori/.env
  api:
    build: ./backend-stori
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./backend-stori/.env
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: