version: '3'
services:
  # app:
  #   build: ./frontend-stori
  #   ports:
  #     - 3001:3000
  #   depends_on:
  #     - api
    # env_file:
    #   - ./frontend-stori/.env
  # api:
  #   build: ./backend-stori
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   # env_file:
  #   #   - ./backend-stori/.env
  #   environment:
  #     DB_MONGO_HOST: db
  #     DB_MONGO_USER: ander
  #     DB_MONGO_PASSWORD: password123
  #     DB_MONGO_PORT: 27017
  #     DB_MONGO_NAME: stori
  db:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ander
    #   MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
  data-volume: