export const ARGUMENT_INVALID = 'GENERIC.ARGUMENT_INVALID';
// export const ARGUMENT_NOT_PROVIDED = 'GENERIC.ARGUMENT_NOT_PROVIDED';
export const INTERNAL_SERVER_ERROR = 'GENERIC.INTERNAL_SERVER_ERROR';
export const NOT_FOUND = 'GENERIC.NOT_FOUND';
